apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee-cafe
  namespace: default
spec:
  selector:
    matchLabels:
      app: jakartaee-cafe
  replicas: 2
  template:
    metadata:
      name: jakartaee-cafe
      labels:
        app: jakartaee-cafe
    spec:
      containers:
      - name: jakartaee-cafe
        image: ${your.docker.hub.id}/jakartaee-cafe:v1
---
apiVersion: v1
kind: Service
metadata:
  name: jakartaee-cafe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jakartaee-cafe
