apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payara-cafe
  namespace: default
spec:
  selector:
    matchLabels:
      app: payara-cafe
  replicas: 2
  template:
    metadata:
      name: payara-cafe
      labels:
        app: payara-cafe
    spec:
      containers:
      - name: payara-cafe
        image: ${login.server}/payara-cafe:v1
---
apiVersion: v1
kind: Service
metadata:
  name: payara-cafe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: payara-cafe
